### ISSUE TITLE
Unsupported platform: Windows_NT x64

### ISSUE THREAD

**Issue by coolsnake** [near/near-sandbox-js#3]
I want to install sandbox in windows 10 and got following error:

$ npm i -g near-sandbox
npm ERR! code 1
npm ERR! path d:\nodejs\node_global\node_modules\near-sandbox
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node ./install.js
npm ERR! d:\nodejs\node_global\node_modules\near-sandbox\dist\getBinary.js:13
npm ERR!     throw new Error(`Unsupported platform: ${type} ${arch}`);
npm ERR!     ^
npm ERR!
npm ERR! Error: Unsupported platform: Windows_NT x64
npm ERR!     at getPlatform (d:\nodejs\node_global\node_modules\near-sandbox\dist\getBinary.js:13:11)
npm ERR!     at AWSUrl (d:\nodejs\node_global\node_modules\near-sandbox\dist\getBinary.js:16:30)
npm ERR!     at getBinary (d:\nodejs\node_global\node_modules\near-sandbox\dist\getBinary.js:27:19)
npm ERR!     at Object.<anonymous> (d:\nodejs\node_global\node_modules\near-sandbox\dist\install.js:4:27)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1105:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:102:18)

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node_cache\_logs\2022-05-18T09_18_38_662Z-debug-0.log

**Comment by coffeedome** [comment]
@frol @rmuftiev  This is also an issue for MacOS x64/intel. Same error. Sharing workaround here using docker https://github.com/coffeedome/near-quickstart-docker-example/blob/main/README.md
